author = "Bruno Amaral"
baseURL = "https://gregory-ms.com/"
copyright = ""
DefaultContentLanguage = "en"
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en"
theme = ["NowUI-Pro"]
title = "Multiple Sclerosis research by Gregory MS"
removePathAccents = true
# Set the default site thumbnail

# Google 
googleSiteVerification = ""
# googleTagManager = ""
headerPhoto = ""

[outputs]
    home = [ "HTML", "RSS", "JSON" ]
    section = [ "HTML", "RSS"]
    term = [ "HTML", "RSS"]

[params]
  defaultImage = "/gregory-thumb.png"
  author = "Bruno Amaral"
  enableComments = false 
  defaultAuthor = "authors/bruno-amaral"
  description = "An index engine for articles and clinical trials around Multiple Sclerosis"
  disqus = ""
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = false
  favicon = "favicon.ico"
  lazyImage = true
  logo="Gregory_Banner3.png"
  showmonth = true
  slogan = ""
  startyear = "2021"

[params.valine]
  appId = ''
  appKey = ''
  avatar = 'robohash'
  debug = true
  enable = false
  enableHeaderVisitor = true
  lang = 'en' # zh-CN
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  visitor = true
[params.options]
  hideSubscribeForm = false

# [menu]
  [[menu.main]]
  name = 'Home'
  url = "/"
  weight = 1

  [[menu.column_2]]
  name = 'Lisbon Collective <i class="fas fa-external-link-square-alt"></i>'
  url = "https://lisboncollective.com"
  [[menu.column_2]]
  name ='OneOverZero <i class="fas fa-external-link-square-alt"></i>'
  url = "https://github.com/oneoverzero"
  [[menu.column_2]]
  name = '<img src="/images/powered_by_project_galileo.png" alt="Support by CloudFlare, Project Galileo" loading="lazy" />'
  url = 'https://www.cloudflare.com/en-gb/galileo/'
  [[menu.column_2]]
  name ="Bruno Amaral"
  url = "https://brunoamaral.eu/"
  [[menu.column_3]]
  name = "Website stats"
  url = "https://analytics.gregory-ms.com/share/bEuESUpF/GregoryMS"
  weight = 9

[social]
  github = "https://github.com/brunoamaral/gregory"
  rss = ""

[taxonomies]
category = "categories"
# source = "source"
# trial_source = "trial_source"
article_source = "article_source"
author = "authors"
tag = "tags"
trial_source = "trial_source"


[permalinks]
  article_source = "/articles/source/:slug"
  trial_source = "/trials/source/:slug"

  # post = "/:slug/"
  # page = "/:slug/"
  # category = "/:slug/"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|GETENV)$']
  [security.funcs]
    getenv = ['^HUGO_|SLUG']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
[build]
  writeStats = true